name: impaktfull_cli
description: A cli that combines all tools for development, testing, ci/cd,...
version: 0.9.0
repository: https://github.com/impaktfull/impaktfull_cli
environment:
  sdk: ^3.0.0
dependencies:
  args: ^2.4.2
  http: ^1.1.0
  meta: ^1.1.0
  path: ^1.8.3
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.0
dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
